### ISSUE TITLE
Error minSdkVersion in projects that use minSdkVersion 16 I hope this library support minSdkVersion

### ISSUE THREAD

**Issue by MashudiSudonym** [inibukanadit/raja-api#3]
I encountered this error, I hope this library supports MinSdkVersion 16, the project I target is to run on API level 16 and the latest. but if I have to update my minSdkVersion, I hope there is a clear reason why I should increase the minimum version of my project sdk.

`Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library [com.github.inibukanadit:raja-api:0.0.1] C:\Users\muham\.gradle\caches\transforms-1\files-1.1\raja-api-0.0.1.aar\6c5891b23e3ef766625913a9b03c7fbc\AndroidManifest.xml as the library might be using APIs not available in 16
	Suggestion: use a compatible library with a minSdk of at most 16,
		or increase this project's minSdk version to at least 19,
		or use tools:overrideLibrary="me.inibukanadit.rajaapi.wilayah" to force usage (may lead to runtime failures)
`

**Comment by addeeandra** [comment]
Thank you, this library has minSdkVersion 19 .. will update it soon to support lower version

**Comment by MashudiSudonym** [comment]
Thanks for fix this
